---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable discovery daemon to find devices
    enableDiscoveryDaemon: true

    # CSI driver settings
    csi:
      enableRbdDriver: true
      enableCephfsDriver: true

      # Talos Linux compatibility - use hostPID for proper device access
      pluginTolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists

      provisionerTolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
