creation_rules:
  - path_regex: clusters/.*/talos/talsecret\.sops\.yaml$
    pgp: 6636CBF9CE1DE1A8
  - path_regex: secrets\.sops\.yaml$
    pgp: 6636CBF9CE1DE1A8
  - path_regex: infrastructure/.*\.sops\.yaml$
    pgp: 6636CBF9CE1DE1A8
