---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-config
  namespace: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-data
  namespace: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
