---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  values:
    config:
      oidc:
        callbackURL: https://homelab-headlamp.ktz.ts.net/oidc-callback
