---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: csi-driver-smb
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
