---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jellyfin-cifs
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media-pv
    volumeAttributes:
      source: "//10.42.1.137/rust_media"
    nodeStageSecretRef:
      name: jellyfin-cifs-credentials
      namespace: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: jellyfin-cifs
  volumeName: jellyfin-media-pv
