---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # Reef is the current stable release
    image: quay.io/ceph/ceph:v18.2.4
    allowUnsupported: false

  dataDirHostPath: /var/lib/rook

  monitoring:
    enabled: true

  mon:
    count: 3
    allowMultiplePerNode: false

  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: pg_autoscaler
        enabled: true

  dashboard:
    enabled: true
    ssl: false

  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false

  crashCollector:
    disable: false

  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    # Per-node device config - Samsung NVMe data disks have different paths per node
    nodes:
      - name: m720q-1
        devices:
          - name: nvme0n1  # Samsung MZVKW512HMJP
      - name: m720q-2
        devices:
          - name: nvme1n1  # Samsung SSD 970 PRO
      - name: m720q-3
        devices:
          - name: nvme1n1  # Samsung SSD 970 PRO

  resources:
    mgr:
      limits:
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    mon:
      limits:
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    osd:
      limits:
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "2Gi"

  # Talos Linux compatibility
  placement:
    all:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
