---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: m720q-k8s-api
  namespace: tailscale
spec:
  type: kube-apiserver
  replicas: 2
  tags:
    - "tag:k8s"
    - "tag:k8s-operator"
    - "tag:k8s-m720q"
  kubeAPIServer:
    mode: auth
