apiVersion: ENC[AES256_GCM,data:VZ0=,iv:1ZtD5w5A1jcDYALnZx5OCKNsOYQf9Xw3ebKAIOL9nsk=,tag:d8Fu0olHQle80YGYrDROsw==,type:str]
kind: ENC[AES256_GCM,data:BvN55nLF,iv:LJEVQoonHBJbrLzXd1YwZ+nSeeAkhc8qNWv9kjR7vtU=,tag:Llt74iK5pNJw/U9lBACDDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3fnS7RzxESce6+yBIA==,iv:wusbe7U0g611giDjj9OA/y2T1KHRHDB96E2MWCAyGLQ=,tag:dIuzwMUuaRtHIs6h2b8Z9w==,type:str]
    namespace: ENC[AES256_GCM,data:bfEu36hzGwo=,iv:1JjlozJMAE82tRxtkLtEqDr0XgxTpJ7vR3ocIG7JqWQ=,tag:ozXZKk2NgqnEVkJJ1lmp4g==,type:str]
type: ENC[AES256_GCM,data:SrCxAWdv,iv:9eWJmwkfpRamAz3Q5HCkKrv2RYV64MKRR7fBnQEsFVo=,tag:Rvb+TWMzWcRNmMkoosZpYg==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:hDNIkFSleT9MizofaaTRw8sJH2PAp/ElbzvlVM2A2So=,iv:8r8webwJoATLPyO0gaVbX9cBIElIBDgZgUjUBpbJYLc=,tag:2jprNjPQszXm/fz/ZxZ0wA==,type:str]
    clientSecret: ENC[AES256_GCM,data:wQVD8/E10kt/1G2yPPQvH9D5JKj7v5ErFB1DloZsOCjORa6Vd4sk+fwot7qPL0OycaMz5Z+qZ6bEU0MjNEZu9w==,iv:NeMLXMKU3s7LZGxs9x72DF5Ole2YZ0RNlLOzcQb5nko=,tag:bGCBINKtE0vKW3bkoQXPOw==,type:str]
    issuerURL: ENC[AES256_GCM,data:abeMN0vdCn3oLzWnwbBRalaOynT1yw==,iv:eje9nldzkiP7R7DmtHqg3t5RjGA2Lx4gMlY98EA5LTk=,tag:n0lHWq03PbaugQHnYv9/XA==,type:str]
    scopes: ENC[AES256_GCM,data:zNK9NW2btJ/B+iAdkm9tSoZYe/Y=,iv:ZwQNoZr+X5P3pbCDYaOaVElHA3pNwNwFvoQvLF3gszM=,tag:v+ZAG66wwfKwKsGNz73xvA==,type:str]
sops:
    age:
        - recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aHZRWmlIYjV6NEcwWVg3
            cWtnZnRLb2oyTmF6NUFXM2FPeUdVaFV4RmpzCnh3dlFVU00yTHoxWDEzSjc1OXVv
            c3hvc0R5aWx6MUdJcU4zK2RwZ0tOMzAKLS0tIEVQMXVVaU1NNjBVdnkyYXZRNzJh
            ZjkrSkNQcS9QRW41YVZrTHhOcmJvakEKfj3r5gI1OeQgMPEjDIp8jClOBhXoxXaE
            DBxpik4D3oc5Pp2Sxdbet3uPL+FRqfkt/go6tXqnPUHdy/K5zu7ZDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T14:18:26Z"
    mac: ENC[AES256_GCM,data:IgsdHQYC0elQsWzA2oxiFCW0FO8H+12I7RcZkmNxlizXq+oVPmHUBlqZakhB77A3GDKv+z2qifG4tqcgscyF4W8BgeEPMsj1tOUp/oWcOzE6Ihq6s+VRsKQqLN04ZpqMH/OKQNeafE786irixjkst1CIrY1bxfZ9JgWm77uVSV8=,iv:YAvK5X9yCUPVuqlQr53a05HbwCD0rSbs8Jkl00FmqQg=,tag:UB0whRk3rLz2LQyWYfNP+Q==,type:str]
    pgp:
        - created_at: "2025-11-29T14:18:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxQ26yvYdZ3KAQ/+LO1xGxWerIxWgBsfzupaPK8uCqaC/nektwoiYJp6PMil
            Wo7IxWjJH5iy35l+kWBHbu9P5okdF2EA292+8uv3cmAMLFDs3kdIiUwdfwy0HtS+
            L5oNoaBIpR8S0agVbJ9kvqnB2z+WDCZcbgeFPlOarK49gLR+lnxXJWMWfckpyAOO
            EkM6dcFP7OVyo2vqjRZKC12tHqcqldxpDWnZx5QyT5X3DYND++qckBFKukcXIuMG
            lPueAUz8/vCWtdZKL9lJaxsxsNyFkfYKJs86yMZ9T2xp+Mhbcl0MMz0qAcMFoRy0
            ECHcHivey665Dsu7yCYotRc+yNtaGccTyDzPUHCOJJAcHXxy4c9GdcnaCMns1MLW
            UjLVPiWfCMHUevIKI/05VF07IuQgqLAnxBaFGsmRyngIyBpW4dVbDpEB3tcV6c7T
            Im5SzTPWY5xR2pyxIow+lF/fh8c7CdDBphZnMbVIjJGGaXeUPW/vDZjgXaXv58q3
            8kq2qmAz5DqYP83Dvn1hccCeDk10Skg8fp5kOF8wWl7FPH3nh+cYTusjHQmfEIv3
            nufH0aYBIG/BLYTbzYcmt+3IPvk2XMogYFlAOgiFqPmnT7+ROrwepj9Smdt7nsNF
            FhG6zhHbCSYeuxsrBNZofH8mtV33/Zc5X9aC4KEOKoytogw6KihENWXfmdtp2yXS
            XgHClFv7efXDbu44ds+2bMb0oNP6dr7vllFAGd27CYdgCczuFD9ua9UM03P+FHpX
            XApn2CcpbiUC+VyFVxrulAajD7DOR/wYR9uKA8ZwSDj+F3j1buY55bov8+lkI4Q=
            =TxfN
            -----END PGP MESSAGE-----
          fp: 6636CBF9CE1DE1A8
    unencrypted_suffix: _unencrypted
    version: 3.11.0
