apiVersion: ENC[AES256_GCM,data:h0c=,iv:oqwkhPhtB9zNqya10qm3P0YxQ+J8EvBzhgaoYMuQJCk=,tag:0rvSWjqW4rehH1RrIqdeyA==,type:str]
kind: ENC[AES256_GCM,data:nbQjwlq3,iv:Q0y6x+NDEwLqkWNtULcJjQVmDQY4CWEJNnKnU0ntlqY=,tag:dspKs5E9wFiIwWlasrBriw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W345S3oVqScA571EcQ==,iv:a/IQlHyg5HV82fS+Zxco1tJKHJWUt6miHqvnsGlDP2A=,tag:zajwPydmn8SZwE21a4mBvQ==,type:str]
    namespace: ENC[AES256_GCM,data:Lt7y4qZPYgY=,iv:sXSTUkP7WEGb3WO32W1aEk/JypfJmyisZFW+Bx/7Q6A=,tag:bzQ87EQdFdhATUET8zPGNA==,type:str]
type: ENC[AES256_GCM,data:0snBBiML,iv:qT+S+T7PszQvy/CkJ0+pG1L1kmzZGWrJVfHwiKq4k+c=,tag:qqsuOYZeh+toXRp4MiufFg==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:6q+D1rXkSfBBM+ltmTn5AxHu0mEaumSakpPEYd8SJuM=,iv:h4mOBxQVv3f6f9qcnWHP21KfmObUhmOKWG9KdR730p0=,tag:fT2uXeyEzNi3wqaRKH7iaA==,type:str]
    clientSecret: ENC[AES256_GCM,data:iwECCYlCiKxucThun5CIMhyCcoKwwEebeD+m1E9rYwqs6h0P+lV1TzCvyasVE3moyTf99etpWnSb+Iz1gAbamQ==,iv:enT2LgGZ3NMOVeZSACL6B+8Xo9sbvtLsWvzJdxs+sdk=,tag:By9R9XL4TGDTc6sP7UQHXg==,type:str]
sops:
    age:
        - recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjVQek9TSjl5cDZEdXJH
            WFBvSmVRV1VHMlFGWkovNTkzMUZGSlhWQ2tzCnFJaEtIa2xmSHdjOTllTGxxSGpk
            UnVqMFhucS9kcGhYQnkzVzBQZVFTbTAKLS0tIGdHMjNibm01Wnk4ZjZTYTNrNlBG
            OXdXMjZVRmNsaENmK3lYUzliS3o0bFkK2sAhArM6z6KFno2sIgdLy87ImGWlUT2Q
            Ehmh/KNAOD1/3tK0A/5zP8SDz1HgbzOWCe4u2tI612IEX9eATFD+qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T14:10:53Z"
    mac: ENC[AES256_GCM,data:FftY21WO8JrX/V4unvBWtXQ7PZn7aee6MksrN6aZkbKVO4uxSBSGTmLMzL3QniKU/h4RoPSnRQr+oCFD2MF8GGgpJ+ffIEcXVNX460jnHyCgV+ZTokoHgh2lexELp4pxB0Pjxi4RxvVNcYvErzeoNv5HtxifFUguVL27ND2naN8=,iv:8o4CO8kbs4H3t0TCjIL2u5hclm2qxMJz1IK4tHLuf/s=,tag:ZcGulOrNoi5kVBkFSbpr/g==,type:str]
    pgp:
        - created_at: "2025-11-29T14:10:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQILAxQ26yvYdZ3KAQ/4s2fc/sK6waWkoY/+n4ok2FrT20sVSNdd5Kn6e3v/mrHo
            Aq8Z5bi3LqhPYwcJ4eXIE+tnZ/kJHzNHrY5LS0R7Zw6D5AnEcWinjVm7aeEqFtjD
            eUnKRFP7lyVgPVsEO0gBbL/tbMSsrLzH33n6Sb+PStzoFcIBgirQ+xwLt1GkRoUr
            Wz0OHi/2iVR3uuq+PhnSk0FQ0clXE2knLUcd/PJjPhYrJFrZTB5KeIvjx7nU3Bfr
            zr5+uocza/bLXsfvyc65Gb2sjB+VXc1Hb5H2KrWRe+7exrKAQwX01/xldXYfHNNB
            abmqe05YzYskNtSwvT+luGuwS38cVRhPbwIV8FfgKY8WYUDGC5G3J16M8OkeUFYJ
            eHdPayt4n4mxaDe1+8XOAIjP+iVPXMFq/37LLVDXEoAosnYMpu00My3XskVE+yRm
            rwRxLh6GOHeZgds0TpYMZMhjCh9EwDWO+LT45hAV9Zx12RIJPOquQkP3zXB/Vg4k
            QSf1E4na0Eec4x+2/3eZmbWuR7WlYl+vr1XqsM2UesK/nfT/OD/l3BazXC++ywQx
            yw4Wt21TwQZwzS2Bfs8slS7T3vEWeQ1LPGmlU4AAYPkFLAke6Ld1EA+N8sSVfjUz
            dBivbTubkss1J+hBTojv4mR4SOn3b5elHTL8ves+omFq0sx56sMZ3UnnhiBsQtJe
            ASzXYVgSw7ZXFs8OApLS4bwjeChD0HB1nqvK+y5YZfJwC3FW3nchj3WsOeuNiEIW
            imOdqVQ3wYMso/SzuQIYQ/Mn0VUDRodnSa1OZ4rAVDy9Z0Zl5TEfdt7ZVn3bUA==
            =Sc1r
            -----END PGP MESSAGE-----
          fp: 6636CBF9CE1DE1A8
    unencrypted_suffix: _unencrypted
    version: 3.11.0
