#!/usr/bin/env bash
set -euo pipefail

# Sync talconfig.yaml with Terraform state
# This script generates talconfig.yaml based on actual VM IPs from Terraform

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TERRAFORM_DIR="${PROJECT_ROOT}/terraform"
TALCONFIG="${PROJECT_ROOT}/talconfig.yaml"

# Source S3 backend credentials
if [[ -f "${TERRAFORM_DIR}/.envrc" ]]; then
  cd "${TERRAFORM_DIR}"
  source .envrc
  cd "${PROJECT_ROOT}"
fi

# Determine which var file to use
VAR_FILE_ARGS=()
if [[ -f "${TERRAFORM_DIR}/secrets.tfvars" ]]; then
  VAR_FILE_ARGS+=("-var-file=secrets.tfvars")
elif [[ -f "${TERRAFORM_DIR}/terraform.tfvars" ]]; then
  VAR_FILE_ARGS+=("-var-file=terraform.tfvars")
fi

echo "🔄 Refreshing Terraform state to get latest VM IPs..."
if ! tofu -chdir="${TERRAFORM_DIR}" refresh "${VAR_FILE_ARGS[@]}" > /dev/null 2>&1; then
  echo "⚠️  Warning: Terraform refresh failed. Using existing state..."
fi

echo "📊 Extracting VM information from Terraform state..."
TF_OUTPUT=$(tofu -chdir="${TERRAFORM_DIR}" output -json)

# Extract node data (hostname and IP) from Terraform outputs
CP_NODES=$(echo "$TF_OUTPUT" | jq -r '.control_plane_vms.value | to_entries | map({name: .key, ip: .value.ip}) | .[]' | jq -s '.')
WORKER_NODES=$(echo "$TF_OUTPUT" | jq -r '.worker_vms.value | to_entries | map({name: .key, ip: .value.ip}) | .[]' | jq -s '.')

# Get first control plane IP for endpoint
ENDPOINT_IP=$(echo "$CP_NODES" | jq -r '.[0].ip')

echo "  Control Plane nodes: $(echo "$CP_NODES" | jq -r '.[].name' | tr '\n' ' ')"
echo "  Worker nodes: $(echo "$WORKER_NODES" | jq -r '.[].name' | tr '\n' ' ')"

# Talos factory image with qemu-guest-agent extension
# Generate at: https://factory.talos.dev/?arch=amd64&extensions=siderolabs%2Fqemu-guest-agent&version=1.11.5
TALOS_VERSION="v1.11.5"
FACTORY_IMAGE="factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:${TALOS_VERSION}"

# Generate talconfig.yaml header
cat > "${TALCONFIG}" <<EOF
# Auto-generated by scripts/talhelper-sync-ip-info.sh
# Source: Terraform state from ${TERRAFORM_DIR}
clusterName: talos-cluster
talosVersion: ${TALOS_VERSION}
endpoint: https://${ENDPOINT_IP}:6443
talosImageURL: ${FACTORY_IMAGE}

nodes:
EOF

# Add control plane nodes
echo "$CP_NODES" | jq -r '.[] | "  - hostname: \(.name)\n    ipAddress: \(.ip)\n    controlPlane: true\n    installDisk: /dev/sda\n    networkInterfaces:\n      - interface: eth0\n        dhcp: true\n"' >> "${TALCONFIG}"

# Add worker nodes
echo "$WORKER_NODES" | jq -r '.[] | "  - hostname: \(.name)\n    ipAddress: \(.ip)\n    controlPlane: false\n    installDisk: /dev/sda\n    networkInterfaces:\n      - interface: eth0\n        dhcp: true\n"' >> "${TALCONFIG}"

echo "✅ Generated ${TALCONFIG}"
echo ""
echo "Next steps:"
echo "  just talgen  # Generate Talos configs"
echo "  just talos   # Apply configs to cluster"
