---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 15m
  chart:
    spec:
      chart: headlamp
      version: ">=0.20.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clusterRoleBinding:
      create: true
    config:
      oidc:
        issuerURL: https://idp.ktz.ts.net
        scopes: "openid profile email"
        # callbackURL set in overlay
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-oidc
