apiVersion: ENC[AES256_GCM,data:XTA=,iv:CavYkQVjnHk8MfWAg94UZI1E9m2qwSJ+7vgcyLJ8uDQ=,tag:OhWAkuarwlL/oVRXD5Jh4A==,type:str]
kind: ENC[AES256_GCM,data:F2NOSg4s,iv:l7EMnbZrtG3DZpoaIxuD/NFpBtAi2X2LwHYPLLu51yw=,tag:95fk3cLglWrVY+jjGlKKPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/vyQC8N/q9DM3D6mjY/8,iv:7qnfdV3P9tUnTO6UgjZFFxM4nm8Tck0gbq46b3HWvyQ=,tag:OLYI7d8GKHDBzRzACSrKuQ==,type:str]
    namespace: ENC[AES256_GCM,data:Gl44upYwbZhL,iv:7N3X8E/jiVpfZr1T81NjIzSve4lEuevZfhoAfI4fttU=,tag:gh58mIXdr2N7fD/js9werQ==,type:str]
type: ENC[AES256_GCM,data:fc0VCuOS,iv:bNdfeNJlriUyHhG5R4pOt3dydC7Iii9E45EAwAEUlGg=,tag:rT6oVbGgrqVWtvDosUsCvQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:KgZq2B1d1V90B+FsdLhnOx0=,iv:0V2FaVJo44weZYMlQg6EnsBmrwWa6ZIEMzdx0RwlQEE=,tag:6hOyZUpL/ytlEyUWID5adQ==,type:str]
    client_secret: ENC[AES256_GCM,data:hf2OsjLxKJtPjMGuwxhAVIuqgqn+eChT/FNGiQX7/PgVKdXpajel/E0bBlXtACoDjeMrqYex/mFh9DG4tTvq,iv:T4uSsGUbWKOQ0OGRbWMV/Q9jqQh1OyOBbh77YslMV3w=,tag:jG4qsImfPHGD3K/X7eR1cg==,type:str]
sops:
    age:
        - recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR1Q0Wm1SbHlMUXFWME1Z
            VGwzVmVrRmVlUzIyanpiYnRxZmVsY1lNSVRZClVaTHc4SGlLTDJXNWJraTM0QnU5
            Nk9vSitYeUlsS0xxejB4QSsyUklmUDAKLS0tIHBNTGMwZTJRekYzdHNXRHdneWR0
            dUZwVHprQ1IvSENhSGtTTXZjMCtsQkUK6B6FXL/E1WxONACFVNCIntqpoNG/qxk4
            lgRq8HFRsyVJhlVVaAr4DePXxUk3gaek9EqGU3xBPgXOY+v2RSaiHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T17:52:56Z"
    mac: ENC[AES256_GCM,data:DCmjQ5Pxnxw5UeTKqTBOnhYklekXIOt24/KiNeIUXScFfVEIa20v6KcPaf+Av6hrijsplQO8/l9GODJWWyjzrfJX8wGCSEjgKHg3X/g5RWaDoxhxQ5mwymYNNBlYZWAFk6zVqP8OuJ9wNXqbjRjVG9lvHE/j7auHg4tCrjGcE28=,iv:MX5/MkgaI08AGZJ2HhZsGKh7orED+B7KrsOZX8t6zsg=,tag:4Ql0hEVzEguL1T1HWh+9mw==,type:str]
    pgp:
        - created_at: "2025-11-25T04:21:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxQ26yvYdZ3KAQ//VCw1SvMM+FKK2mr13bTjsFn8R/fLCu6j06/gFShFst0b
            TQtttu7hzKVDq6sNkYvuQEwIsJicm4z5Pj3MFVPs/Pk4w1JNzuxvpEDL2TfM3t8E
            W6IQ+6RCU6GQKHO2+L4tduloVFuna/MZJyTJAVP1ycw5KkoKnGM/lEXabIK52gHp
            J7v/qeqMoALDdSktCgbSMh3a0xim6V2qXzy5SQlpX3O93Vq7yxd99ni8oWSKhrDP
            WimXrvUAaTjhY1ZsgyyrjwdiXUEQgvWbjUf/Vijl6xecE0pKRnmVB+vWwng/bLDB
            75HUy2X9krI2E6rv9umppMERGl8IWI6aS0Zo10Jcsk1zFOldYZdRNRRPgXOBElLd
            4NZEUBUfQCcjNx4NmmZxiPBVu4xbwIv3sU9oc0dWjztU5WlEUChaXuufVon/hXck
            TZjVCXXQmR4qUwGgtBC1zUw4TxCAygKVO+s/yIZfTKc7xXELqE3moiY9DQ4W+vVB
            WnZMP/Xa/7L7u9LzyukJGO56mUOFZ7z0Ukve8xNvvIJsvZpRS6eW1YP2TpYYgGTS
            YhVXCigzCbnR4joOfklrrepS8Cvpz0VsazsHkFQnFxKWseGSUgqHvMFRWn4HXau4
            tIqcrT+MCp0hEYakr/QdfhItiIdyxbgkv5B/gf6+mrt2qeKdp9OeEoTf0VkGCmnS
            XgFFQ2Sz5QaSWHm9Znou5Au1XVd9/h+Ui1GW+89z85HxecxOFAZfdREXKI/I0zlc
            ANuZisfbJGlh/DURu05UruOQnf05LgM8bcnkQ0Ogzz56pFm+lWW4xtoAZA2EQJA=
            =Urjl
            -----END PGP MESSAGE-----
          fp: 6636CBF9CE1DE1A8
    unencrypted_suffix: _unencrypted
    version: 3.11.0
